package com.qf.dao;

import com.qf.pojo.po.UserImg;
import com.qf.pojo.po.UserImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    long countByExample(UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int deleteByExample(UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int insert(UserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int insertSelective(UserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    List<UserImg> selectByExampleWithBLOBs(UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    List<UserImg> selectByExample(UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    UserImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserImg record, @Param("example") UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") UserImg record, @Param("example") UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int updateByExample(@Param("record") UserImg record, @Param("example") UserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int updateByPrimaryKeySelective(UserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_img
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(UserImg record);
}