package com.qf.dao;

import com.qf.pojo.po.UserAuthor;
import com.qf.pojo.po.UserAuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    long countByExample(UserAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int deleteByExample(UserAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int insert(UserAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int insertSelective(UserAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    List<UserAuthor> selectByExample(UserAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    UserAuthor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") UserAuthor record, @Param("example") UserAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") UserAuthor record, @Param("example") UserAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(UserAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_author
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(UserAuthor record);
}