package com.qf.pojo.po;

import java.util.Date;

public class UserAuthor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.user_info_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String userInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.author_type
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String authorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.type_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.command
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String command;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.identify
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Boolean identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_author.update_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.id
     *
     * @return the value of user_author.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.id
     *
     * @param id the value for user_author.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.user_info_id
     *
     * @return the value of user_author.user_info_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.user_info_id
     *
     * @param userInfoId the value for user_author.user_info_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setUserInfoId(String userInfoId) {
        this.userInfoId = userInfoId == null ? null : userInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.author_type
     *
     * @return the value of user_author.author_type
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getAuthorType() {
        return authorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.author_type
     *
     * @param authorType the value for user_author.author_type
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setAuthorType(String authorType) {
        this.authorType = authorType == null ? null : authorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.type_id
     *
     * @return the value of user_author.type_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.type_id
     *
     * @param typeId the value for user_author.type_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.command
     *
     * @return the value of user_author.command
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.command
     *
     * @param command the value for user_author.command
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.identify
     *
     * @return the value of user_author.identify
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Boolean getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.identify
     *
     * @param identify the value for user_author.identify
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setIdentify(Boolean identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.status
     *
     * @return the value of user_author.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.status
     *
     * @param status the value for user_author.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_author.update_time
     *
     * @return the value of user_author.update_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_author.update_time
     *
     * @param updateTime the value for user_author.update_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}