package com.qf.pojo.po;

public class UserImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_img.id
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_img.img_url
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_img.id
     *
     * @return the value of user_img.id
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_img.id
     *
     * @param id the value for user_img.id
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_img.img_url
     *
     * @return the value of user_img.img_url
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_img.img_url
     *
     * @param imgUrl the value for user_img.img_url
     *
     * @mbg.generated Sat Dec 22 22:05:05 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}