package com.qf.pojo.po;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.area
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.country
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.level
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.avatar
     *
     * @return the value of user_info.avatar
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.avatar
     *
     * @param avatar the value for user_info.avatar
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.area
     *
     * @return the value of user_info.area
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.area
     *
     * @param area the value for user_info.area
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.country
     *
     * @return the value of user_info.country
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.country
     *
     * @param country the value for user_info.country
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.level
     *
     * @return the value of user_info.level
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.level
     *
     * @param level the value for user_info.level
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Dec 19 22:31:05 CST 2018
=======
     * @mbg.generated Thu Dec 20 09:31:38 CST 2018
>>>>>>> Stashed changes
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}